#!/usr/bin/env python3
"""Interactive local configuration for the one-command node bootstrap."""
import getpass
import argparse
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import sys

ROOT = Path(__file__).resolve().parents[1]
NODES = {"storage": "storage_nodes", "apps": "app_nodes", "infra": "infra_nodes"}
SCHEDULES = {"5min", "hourly", "daily", "weekly", "monthly"}


def update_settings(previous, schedule=None, update_time=None):
    schedule = schedule or ask("Update schedule: 5min, hourly, daily, weekly, monthly",
                               previous.get("bootstrap_update_schedule", "weekly"),
                               lambda value: value in SCHEDULES)
    update_time = update_time or ask("Update time (HH:MM; weekly is Monday, monthly is the first)",
                                     previous.get("bootstrap_update_time", "03:00"),
                                     lambda value: bool(re.fullmatch(r"(?:[01]\d|2[0-3]):[0-5]\d", value)))
    if schedule not in SCHEDULES or not re.fullmatch(r"(?:[01]\d|2[0-3]):[0-5]\d", update_time):
        raise ValueError("Invalid schedule or time")
    return {"bootstrap_update_schedule": schedule, "bootstrap_update_time": update_time}


def configure_updates(node="", root=ROOT, schedule=None, update_time=None):
    path = root / ".bootstrap/vars.json"
    data = json.loads(path.read_text())
    if node and node != data["bootstrap_node"]:
        raise ValueError("This checkout is already configured for a different node")
    data.update(update_settings(data, schedule, update_time))
    save_json(path, data)


def read_env(path):
    values = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if not match:
            continue
        key, value = match.groups()
        value = value.strip()
        if len(value) > 1 and value[0] == value[-1] == "'":
            value = value[1:-1].replace("\\'", "'")
        elif len(value) > 1 and value[0] == value[-1] == '"':
            value = value[1:-1]
        values[key] = value
    return values


def write_env(path, values):
    lines = ["# Generated by bootstrap; local configuration, never commit."]
    for key, value in values.items():
        if "\n" in str(value) or "\r" in str(value):
            raise ValueError(f"{key} must be a single line")
        literal = str(value).replace("'", "\\'")
        lines.append(f"{key}='{literal}'")
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)


def save_json(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n")
    path.chmod(0o600)


def usable(value):
    return bool(value) and "CHANGEME" not in value


def ask(label, default="", validate=lambda value: bool(value)):
    while True:
        value = input(f"{label}" + (f" [{default}]" if default else "") + ": ").strip()
        value = value or default
        if validate(value):
            return value
        print("Please enter a valid value.")


def yes(label, default=False):
    return ask(label + " (y/n)", "y" if default else "n",
               lambda value: value.lower() in {"y", "n"}).lower() == "y"


def ipv4(value):
    try:
        return ipaddress.ip_address(value).version == 4
    except ValueError:
        return False


def cidr(value):
    try:
        return ipaddress.ip_network(value, strict=False).version == 4
    except ValueError:
        return False


def directory(value):
    return value.startswith("/") and bool(re.fullmatch(r"/[A-Za-z0-9_./-]+", value)) and ".." not in Path(value).parts and value != "/"


def credential(key, existing="", generate=False):
    if usable(existing):
        return existing
    if generate:
        return secrets.token_hex(32)
    while True:
        value = getpass.getpass(f"{key}" + (" (same password on all three nodes)" if key == "RESTIC_PASSWORD" else "") + ": ")
        if usable(value) and "\n" not in value and "\r" not in value:
            return value
        print("A configured value is required.")


def configure(node="", root=ROOT, schedule=None, update_time=None):
    os.umask(0o077)
    directory_path = root / ".bootstrap"
    directory_path.mkdir(mode=0o700, exist_ok=True)
    profile_path = directory_path / "vars.json"
    previous = json.loads(profile_path.read_text()) if profile_path.exists() else {}
    node = node or ask("Node role: storage, apps, or infra",
                       previous.get("bootstrap_node", "apps"), lambda value: value in NODES)
    if node not in NODES:
        raise ValueError("Node must be storage, apps, or infra")
    if previous.get("bootstrap_node", node) != node:
        raise ValueError("This checkout is already configured for a different node")
    env = read_env(root / ".env.example")
    env.update(read_env(root / ".env"))
    # Reuse credentials from standalone stacks when adopting an existing node.
    vpn_keys = {"VPN_TYPE", "VPN_SERVICE_PROVIDER", "SERVER_COUNTRIES",
                "WIREGUARD_PRIVATE_KEY", "WIREGUARD_ADDRESSES"}
    for example in sorted((root / "stacks" / node).glob("*/.env.example")):
        saved = read_env(example.parent / ".env")
        for key, default in read_env(example).items():
            if ("CHANGEME" in default or key in vpn_keys) and not usable(env.get(key, "")) and usable(saved.get(key, "")):
                env[key] = saved[key]
    print(f"\nConfiguring {node}. Existing credentials are preserved.")
    print("Provision storage first, then apps and infra.")
    addresses = {}
    for key, label, default in [
        ("STORAGE_HOST", "Storage node LAN IPv4", "192.168.1.120"),
        ("APPS_HOST", "Apps node LAN IPv4", "192.168.1.121"),
        ("INFRA_HOST", "Infra node LAN IPv4", "192.168.1.122"),
    ]:
        addresses[key] = ask(label, env.get(key, default), ipv4)
    if len(set(addresses.values())) != 3:
        raise ValueError("Each node must have a different LAN address")
    default_net = str(ipaddress.ip_network(addresses["STORAGE_HOST"] + "/24", strict=False))
    lan = ask("LAN CIDR", env.get("LAN_NETWORK", default_net), cidr)
    if not all(ipaddress.ip_address(value) in ipaddress.ip_network(lan, strict=False) for value in addresses.values()):
        raise ValueError("All node addresses must be in the configured LAN")
    storage_media = ask("Media export directory on storage",
                        previous.get("bootstrap_storage_media", "/mnt/nas"), directory)
    storage_backup = ask("Backup export directory on storage",
                         previous.get("bootstrap_storage_backup", "/mnt/hdd2"), directory)
    local_media = storage_media if node == "storage" else ask("Local media mount",
                                                            env.get("MEDIA_ROOT", "/mnt/nas"), directory)
    local_backup = storage_backup if node == "storage" else ask("Local backup mount",
                                                               env.get("NFS_BACKUP", "/mnt/nfs/backup"), directory)
    if local_media == local_backup or storage_media == storage_backup:
        raise ValueError("Media and backups must use different directories")
    data = ask("Local application data directory", env.get("DOCKER_DATA", "/opt/homelab/data"), directory)
    uid = ask("Shared media UID", env.get("PUID", str(os.getuid())), str.isdecimal)
    gid = ask("Shared media GID", env.get("PGID", str(os.getgid())), str.isdecimal)
    tz = ask("Timezone", env.get("TZ", "Europe/Amsterdam"),
             lambda value: ".." not in value and (Path("/usr/share/zoneinfo") / value).is_file())
    deployment_schedule = update_settings(previous, schedule, update_time)
    env.update(addresses)
    env.update(PUID=uid, PGID=gid, TZ=tz, DOCKER_DATA=data, MEDIA_ROOT=local_media,
               NFS_BACKUP=local_backup, RESTIC_REPO_PATH=local_backup + "/restic",
               IMMICH_LIBRARY=local_media + "/Gallery", FILEBROWSER_ROOT=local_media,
               LAN_NETWORK=lan, LAN_CIDR=lan, PIHOLE_HOST_IP=addresses["INFRA_HOST"])
    available = {path.parent.name for path in (root / "stacks" / node).glob("*/.env.example")}
    skipped = set(previous.get("bootstrap_skip", ["portainer"]))
    for stack, label, configured in [
        ("restic", "Enable encrypted backups", usable(env.get("RESTIC_PASSWORD", "")) or "restic" not in skipped),
        ("qbittorrent", "Enable qBittorrent with your VPN account", usable(env.get("OPENVPN_PASSWORD", "")) or usable(env.get("WIREGUARD_PRIVATE_KEY", ""))),
        ("diun", "Enable Diun SMTP notifications", usable(env.get("SMTP_PASSWORD", ""))),
        ("beszel-agent", "Enable Beszel agent (requires the hub's public key)", usable(env.get("BESZEL_AGENT_KEY", ""))),
    ]:
        if stack in available:
            if yes(label, configured):
                skipped.discard(stack)
            else:
                skipped.add(stack)
    optional = {"restic", "qbittorrent", "diun", "beszel-agent", "portainer"}
    prior_extra = sorted(skipped - optional)
    extra_text = input("Additional stack names to skip (space-separated, none clears" + (", current: " + " ".join(prior_extra) if prior_extra else "") + "): ").strip()
    extra = ([] if extra_text == "none" else extra_text.split()) if extra_text else prior_extra
    skipped.difference_update(prior_extra)
    if set(extra) - available:
        raise ValueError("Unknown stack(s): " + " ".join(sorted(set(extra) - available)))
    skipped.update(extra)
    if node == "apps" and "portfolio" not in skipped:
        env["PORTFOLIO_REPOSITORY"] = ask("Portfolio release repository (owner/repo)",
                                         env.get("PORTFOLIO_REPOSITORY", "Abhijith126/portfolio"),
                                         lambda value: bool(re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", value)))
    if node == "storage" and "qbittorrent" not in skipped:
        env["VPN_SERVICE_PROVIDER"] = ask("OpenVPN provider", env.get("VPN_SERVICE_PROVIDER", "fastestvpn"))
        env["VPN_TYPE"] = ask("VPN protocol: openvpn or wireguard", env.get("VPN_TYPE", "openvpn"),
                              lambda value: value in {"openvpn", "wireguard"})
        if env["VPN_TYPE"] == "wireguard":
            env["WIREGUARD_PRIVATE_KEY"] = credential("WIREGUARD_PRIVATE_KEY", env.get("WIREGUARD_PRIVATE_KEY", ""))
            env["WIREGUARD_ADDRESSES"] = ask("WireGuard interface address", env.get("WIREGUARD_ADDRESSES", ""))
            env["OPENVPN_USER"] = ""
            env["OPENVPN_PASSWORD"] = ""
        env["SERVER_COUNTRIES"] = ask("VPN country", env.get("SERVER_COUNTRIES", "Netherlands"))
    if node == "infra":
        domain_default = env.get("DOMAIN", "home.arpa")
        if domain_default == "home.example.com":
            domain_default = "home.arpa"
        env["DOMAIN"] = ask("Domain for service URLs", domain_default,
                            lambda value: bool(re.fullmatch(r"[A-Za-z0-9.-]+", value)) and "." in value)
        env["ACME_EMAIL"] = ask("Administrator email", env.get("ACME_EMAIL", "you@example.com"),
                                lambda value: "@" in value)
        env["ROUTER_IP"] = ask("Router LAN IPv4", env.get("ROUTER_IP", str(ipaddress.ip_network(lan, strict=False).network_address + 1)), ipv4)
        if "caddy" not in skipped:
            cloud_path = root / "stacks/infra/caddy/cloudflare.env"
            cloud = read_env(cloud_path)
            mode = ask("TLS mode: internal or cloudflare",
                       "cloudflare" if usable(cloud.get("CLOUDFLARE_API_TOKEN", "")) else "internal",
                       lambda value: value in {"internal", "cloudflare"})
            env["CADDY_GLOBAL_OPTIONS"] = ("local_certs" if mode == "internal"
                                          else "acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}")
            if mode == "cloudflare":
                cloud["CLOUDFLARE_API_TOKEN"] = credential("CLOUDFLARE_API_TOKEN", cloud.get("CLOUDFLARE_API_TOKEN", ""))
                write_env(cloud_path, cloud)
    generated = {"DB_PASSWORD", "PIHOLE_WEBPASSWORD", "HOMARR_SECRET_ENCRYPTION_KEY"}
    for example in sorted((root / "stacks" / node).glob("*/.env.example")):
        if example.parent.name in skipped:
            continue
        for key, value in read_env(example).items():
            if "CHANGEME" in value:
                if key in {"OPENVPN_USER", "OPENVPN_PASSWORD"} and env.get("VPN_TYPE") == "wireguard":
                    continue
                can_generate = key in generated
                protected_data = {"DB_PASSWORD": "immich", "HOMARR_SECRET_ENCRYPTION_KEY": "homarr"}
                if key in protected_data and (Path(data) / protected_data[key]).exists():
                    can_generate = False
                    if not usable(env.get(key, "")):
                        print(f"Existing {protected_data[key]} data detected; enter its current {key}.")
                env[key] = credential(key, env.get(key, ""), can_generate)
    # Optional Tailscale onboarding; the key is removed when the wrapper exits.
    auth_key = getpass.getpass("Optional Tailscale auth key (blank to keep current connection or skip): ")
    distro = read_env(Path("/etc/os-release"))
    release = distro.get("VERSION_CODENAME", "")
    vars_data = {
        **deployment_schedule,
        "bootstrap_node": node, "bootstrap_skip": sorted(skipped),
        "bootstrap_domain": env.get("DOMAIN", "home.arpa"), "bootstrap_infra_ip": addresses["INFRA_HOST"],
        "bootstrap_storage_media": storage_media, "bootstrap_storage_backup": storage_backup,
        "bootstrap_media": local_media, "bootstrap_backup": local_backup,
        "bootstrap_hosts": [{"name": name, "address": addresses[key]} for name, key in
                            [("ryzen", "STORAGE_HOST"), ("apps", "APPS_HOST"), ("infra", "INFRA_HOST")]],
        "homelab_user": getpass.getuser(), "homelab_uid": int(uid), "homelab_gid": int(gid),
        "timezone": tz, "docker_data_root": data, "lan_cidr": lan,
        "enable_portainer_agent": False,
        "enable_tailscale": bool(auth_key) or previous.get("enable_tailscale", False),
        "docker_apt_release": release,
        "tailscale_apt_release": "bookworm" if distro.get("ID") == "debian" and release == "trixie" else release,
        "nfs_server_host": addresses["STORAGE_HOST"],
        "nfs_exports": [{"path": path, "clients": lan, "options": "rw,sync,no_subtree_check,no_root_squash"}
                        for path in [storage_media, storage_backup]],
        "nfs_mounts": [{"src": addresses["STORAGE_HOST"] + ":" + source, "path": destination}
                       for source, destination in [(storage_media, local_media), (storage_backup, local_backup)]],
    }
    write_env(root / ".env", env)
    save_json(profile_path, vars_data)
    save_json(directory_path / "auth.json", {"tailscale_authkey": auth_key})
    inventory = {"all": {"children": {NODES[node]: {"hosts": {"homelab-local": {
        "ansible_connection": "local", "ansible_python_interpreter": "/usr/bin/python3"}}}}}}
    save_json(directory_path / "inventory.json", inventory)
    print("Enabled stacks: " + ", ".join(sorted(available - skipped)))
    print("Skipped stacks: " + ", ".join(sorted(available & skipped)))
    print(f"Configuration saved locally for {node}; secrets are not printed.")


def settings(root=ROOT):
    data = json.loads((root / ".bootstrap/vars.json").read_text())
    return [data["bootstrap_node"], data["bootstrap_media"] + " " + data["bootstrap_backup"],
            " ".join(data["bootstrap_skip"]), data.get("bootstrap_update_schedule", "weekly"),
            data.get("bootstrap_update_time", "03:00"), data.get("timezone", "Europe/Amsterdam")]


if __name__ == "__main__":
    try:
        if sys.argv[1:] == ["--settings"]:
            print("\n".join(settings()))
        else:
            parser = argparse.ArgumentParser(description=__doc__)
            parser.add_argument("node", nargs="?", default="", choices=["", *NODES])
            parser.add_argument("--schedule", choices=sorted(SCHEDULES))
            parser.add_argument("--time")
            parser.add_argument("--updates-only", action="store_true")
            args = parser.parse_args()
            function = configure_updates if args.updates_only else configure
            function(args.node, schedule=args.schedule, update_time=args.time)
    except (ValueError, EOFError, KeyboardInterrupt) as error:
        print(f"Configuration stopped: {error}", file=sys.stderr)
        sys.exit(1)
